### PR TITLE
Add French translations

### PR DESCRIPTION
**Pull request by NathanBnm**
# Changelog

- Added `fr.po` and `extra/fr.po`
- Added fr to `LINGUAS` and `extra/LINGUAS`

# Note

I didn't know how to translate the version names so I left them as they were (With Stereo Sound / Unto The Rocks).

If you want to add "Added : French translations." to changelog you can translate it by "Ajout : Traductions françaises.".

If you want to credit me you can add "Added : French translations thanks to @NathanBnm." which should be translated as "Ajout : Traductions françaises grâce à @NathanBnm.".

**This PR is ready for review**

### CODE REVIEW

**Comment by lainsce** [comment]
Will do. Thanks for the translation!

**Comment by lainsce** [comment]
By the way, version names can be translated literally.

**Comment by NathanBnm** [comment]
But on French that sounds really weird, without real sense xD Maybe It's better to keep it in english

**Comment by lainsce** [comment]
The intention _is_ to be weird. :joy:

**Pull request merged**
